# 交叉验证设置
cross_validation:
  method: 'stratified'  # 交叉验证方法: 'stratified', 'random'
  n_splits: 10  # 折数
  n_repeats: 5  # 重复次数
  random_state: 42

# 超参数优化设置
hyperparameter_tuning:
  method: 'bayesian'  # 优化方法: 'bayesian', 'grid', 'random'
  n_trials: 100  # 优化迭代次数
  n_jobs: -1  # 并行任务数，-1表示使用所有可用CPU
  metric: 'c_index'  # 优化目标: 'c_index', 'time_auc', 'brier_score'

# 评估指标设置
metrics:
  # 判别能力指标
  discrimination:
    c_index: true
    time_dependent_auc:
      enabled: true
      times: [3, 5, 10]  # 评估时间点(年)
  
  # 校准性指标
  calibration:
    brier_score:
      enabled: true
      time_points: [3, 5, 10]  # 评估时间点(年)
    calibration_curve:
      enabled: true
      time_points: [3, 5, 10]  # 评估时间点(年)
      n_bins: 10

  # 临床决策价值
  clinical_utility:
    decision_curve_analysis:
      enabled: true
      time_points: [3, 5, 10]  # 评估时间点(年)
      threshold_range: [0.0, 1.0]
      threshold_steps: 100 