# Cross-validation settings
cross_validation:
  method: 'stratified'  # Cross-validation method: 'stratified', 'random'
  n_splits: 10  # Number of folds
  n_repeats: 5  # Number of repeats
  random_state: 42

# Hyperparameter optimization settings
hyperparameter_tuning:
  method: 'bayesian'  # Optimization method: 'bayesian', 'grid', 'random'
  n_trials: 100  # Number of optimization iterations
  n_jobs: -1  # Number of parallel jobs, -1 means using all available CPUs
  metric: 'c_index'  # Optimization objective: 'c_index', 'time_auc', 'brier_score'

# Evaluation metrics settings
metrics:
  # Discrimination metrics
  discrimination:
    c_index: true
    time_dependent_auc:
      enabled: true
      times: [3, 5, 10]  # Evaluation time points (years)
  
  # Calibration metrics
  calibration:
    brier_score:
      enabled: true
      time_points: [3, 5, 10]  # Evaluation time points (years)
    calibration_curve:
      enabled: true
      time_points: [3, 5, 10]  # Evaluation time points (years)
      n_bins: 10

  # Clinical utility
  clinical_utility:
    decision_curve_analysis:
      enabled: true
      time_points: [3, 5, 10]  # Evaluation time points (years)
      threshold_range: [0.0, 1.0]
      threshold_steps: 100 