# 特征选择设置
feature_selection:
  # 单变量特征选择
  univariate:
    method: 'cox'  # 单变量选择方法: 'cox', 'logrank'
    pvalue_threshold: 0.05  # p值阈值
    fdr_correction: true  # 是否进行FDR校正
    hazard_ratio_filter: true  # 是否基于风险比进行筛选
    min_hazard_ratio: 0.8  # 最小HR阈值
    max_hazard_ratio: 1.2  # 最大HR阈值

  # Bootstrap稳定性评估
  bootstrap:
    n_iterations: 100  # Bootstrap迭代次数
    sample_fraction: 0.8  # 每次抽样比例
    stability_threshold: 0.7  # 特征稳定性阈值

# 特征分组设置
feature_grouping:
  clinical_features: []  # 临床特征列表
  protein_features: []  # 蛋白质特征列表
  # 留空将通过命名前缀或其他方式自动识别 