# Feature selection settings
feature_selection:
  # Univariate feature selection
  univariate:
    method: 'cox'  # Univariate selection method: 'cox', 'logrank'
    pvalue_threshold: 0.1  # p-value threshold
    fdr_correction: true  # Whether to apply FDR correction
    hazard_ratio_filter: true  # Whether to filter based on hazard ratio
    min_hazard_ratio: 0.8  # Minimum HR threshold
    max_hazard_ratio: 1.2  # Maximum HR threshold

  # Bootstrap stability assessment
  bootstrap:
    n_iterations: 100  # Number of bootstrap iterations
    sample_fraction: 0.8  # Sampling fraction for each iteration
    stability_threshold: 0.7  # Feature stability threshold

# Feature grouping settings
feature_grouping:
  clinical_features: []  # List of clinical features
  protein_features: []  # List of protein features
  # Leave empty to automatically identify by prefixes or other methods 