# 基准模型设置
base_models:
  coxph:
    enabled: true
    regularization: 'l1'  # 正则化类型: 'l1', 'l2', 'elasticnet'
    alpha: 1.0  # 正则化强度
    l1_ratio: 0.5  # elasticnet混合参数

  random_survival_forest:
    enabled: true
    n_estimators: 100
    max_depth: 5
    min_samples_split: 10
    min_samples_leaf: 5
    random_state: 42

  coxboost:
    enabled: true
    n_estimators: 100
    learning_rate: 0.1
    dropout_rate: 0.2
    random_state: 42

# 进阶模型设置
advanced_models:
  deepsurv:
    enabled: false  # 默认关闭，仅在样本量足够时启用
    hidden_layers: [64, 32]
    activation: 'relu'
    dropout: 0.1
    learning_rate: 0.01
    batch_size: 64
    epochs: 100

  mtl_cox:
    enabled: false  # 默认关闭，仅在样本量足够时启用
    shared_layers: [64, 32]
    task_specific_layers: [16]
    learning_rate: 0.01
    batch_size: 64
    epochs: 100

# 集成模型设置
ensemble:
  enabled: true
  methods: ['stacking', 'bagging']
  meta_learner: 'ridge'  # meta-learner类型: 'ridge', 'cox'
  use_dynamic_weights: true
  weight_update_frequency: 10  # 动态权重更新频率 