# Base model settings
base_models:
  coxph:
    enabled: true
    regularization: 'l1'  # Regularization type: 'l1', 'l2', 'elasticnet'
    alpha: 1.0  # Regularization strength
    l1_ratio: 0.5  # Elasticnet mixing parameter

  random_survival_forest:
    enabled: true
    n_estimators: 100
    max_depth: 5
    min_samples_split: 10
    min_samples_leaf: 5
    random_state: 42

  coxboost:
    enabled: true
    n_estimators: 100
    learning_rate: 0.1
    dropout_rate: 0.2
    random_state: 42

# Advanced model settings
advanced_models:
  deepsurv:
    enabled: false  # Disabled by default, enable only when sample size is sufficient
    hidden_layers: [64, 32]
    activation: 'relu'
    dropout: 0.1
    learning_rate: 0.01
    batch_size: 64
    epochs: 100

  mtl_cox:
    enabled: false  # Disabled by default, enable only when sample size is sufficient
    shared_layers: [64, 32]
    task_specific_layers: [16]
    learning_rate: 0.01
    batch_size: 64
    epochs: 100

# Ensemble model settings
ensemble:
  enabled: true
  methods: ['stacking', 'bagging']
  meta_learner: 'ridge'  # Meta-learner type: 'ridge', 'cox'
  use_dynamic_weights: true
  weight_update_frequency: 10  # Dynamic weight update frequency 